# LED controller drivers.
if(CONFIG_SENSEWEAR_LP5562_DRIVER)
    file(GLOB _lp5562_src CONFIGURE_DEPENDS ${CMAKE_CURRENT_LIST_DIR}/lp5562/*.c)
    list(APPEND BOARD_DRIVER_SOURCES ${_lp5562_src})
    list(APPEND BOARD_DRIVER_INCLUDE_DIRS ${CMAKE_CURRENT_LIST_DIR}/lp5562)
endif()
