/**
 * Copyright (c) 2026
 * SPDX-License-Identifier: Apache-2.0
 *
 * @file mtch6102.h
 * @brief SensWear MTCH6102 acquisition and one-dimensional slider API.
 * @defgroup senswear_mtch6102 SensWear MTCH6102 touch controller
 * @ingroup io_interfaces
 * @{
 *
 * The shield has 15 separate pads in a line. A valid 12 X / 3 Y controller
 * configuration scans all channels; firmware reads SENSORVALUES and computes
 * touch presence, a physical X coordinate, and gestures independently of the
 * controller's 2D touch/gesture decoder. The pad order from connector to tip is
 * RX0, RX2, RX1, RX3..RX14. Pad centers are x=0..896, 64 units per 3 mm pitch.
 * Y is always zero. See the touch shield README for the hardware references.
 *
 * Call init(), optionally config(), then start(). SYNC falling edges (the end
 * of every acquisition frame) post coalesced mtch6102_Irq events. A 100 ms timer
 * also requests a read to recover after queue overflow or a lost edge. Neither
 * ISR performs I2C or logging. The consumer calls mtch6102_irq_handler(), which
 * reads a complete frame between SYNC edges and publishes a decoded event.
 * Each event owns an immutable sample in p_param: the consumer MUST call
 * mtch6102_release_sample() after use. The bounded pool drops frames if the
 * consumer falls behind; queued samples cannot be overwritten by later reads.
 *
 * The raw TOUCHSTATE byte remains diagnostic. Its TCH bit can disagree with
 * host-derived position.touched on this non-2D board. gesture_state uses the
 * established MTCH6102 byte codes, generated by the host; there are no Y swipes.
 *
 * Hardware operations are serialized and each complete I2C sequence owns and
 * releases sys_i2c. The I2C address is fixed by devicetree and never rewritten.
 * The driver claims daughter_if_GPIO2 (SYNC) and GPIO3 (INT) as inputs. Only
 * SYNC is armed for interrupts. init() enables the 1.8 V supply before
 * probing. stop() selects controller standby and retains rail power to avoid
 * an unpowered controller holding the shared I2C lines. start() restores the
 * configured mode and resets host gesture state.
 *
 * The public BLE layouts remain unchanged. The legacy Y slot is reserved zero;
 * gesture enum values and UUIDs retain their existing encodings.
 */

#ifndef MTCH6102_H_
#define MTCH6102_H_

#include "mtch6102_registers.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <time.h>

#include <zephyr/drivers/i2c.h>

/**
 * @brief Touch-board supply voltage matching its 1.8 V signal domain, in microvolts.
 * @details RESET and I2C are pulled to 1.8 V; SYNC connects directly to the
 *          1.8 V MCU. At the old 2.8 V supply, RESET and I2C high levels were
 *          below the MTCH6102 guaranteed thresholds (0.8/0.7 times VDD).
 *          DS40001750A tables 18-1/18-2 permit 1.8 V operation. Verify actual
 *          VDD/ripple on the assembled board because this is the lower limit.
 */
#define MTCH6102_SUPPLY_VOLTAGE_UV (1800000)

/**
 * @brief Driver-level MTCH6102 event identifiers.
 * @details This is a software event namespace rather than a hardware register
 *          encoding. ::mtch6102_Irq requests a completed acquisition frame; the
 *          `mtch6102_event_*` values map decoded touch state and gesture codes
 *          to stable identifiers for higher-level policy code.
 */
enum mtch6102_event_type {
	mtch6102_event_Invalid = -1,	  /**< No valid event. */
	mtch6102_Irq = 0,				  /**< Coalesced SYNC/recovery acquisition request. */
	mtch6102_event_TouchDetected,	  /**< Host slider touch is present. */
	mtch6102_event_TouchReleased,	  /**< Host slider touch is released. */
	mtch6102_event_SingleClick,		  /**< Gesture code 0x10. */
	mtch6102_event_ClickAndHold,	  /**< Gesture code 0x11. */
	mtch6102_event_DoubleClick,		  /**< Gesture code 0x20. */
	mtch6102_event_DownSwipe,		  /**< Gesture code 0x31. */
	mtch6102_event_DownSwipeAndHold,  /**< Gesture code 0x32. */
	mtch6102_event_RightSwipe,		  /**< Gesture code 0x41. */
	mtch6102_event_RightSwipeAndHold, /**< Gesture code 0x42. */
	mtch6102_event_UpSwipe,			  /**< Gesture code 0x51. */
	mtch6102_event_UpSwipeAndHold,	  /**< Gesture code 0x52. */
	mtch6102_event_LeftSwipe,		  /**< Gesture code 0x61. */
	mtch6102_event_LeftSwipeAndHold,  /**< Gesture code 0x62. */
	mtch6102_event_Count,			  /**< Number of valid event identifiers. */
};

/**
 * @brief Decoded touch sample payload.
 * @details Host-decoded one-dimensional position and gesture code. Each
 *          queued event owns its sample until mtch6102_release_sample().
 */
struct touch_sensor_sample_t {
	time_t timestamp; /**< Timestamp of the sample in microseconds since the Unix epoch. */
	struct mtch6102_position position; /**< Host position and raw controller status. */
	uint8_t gesture_state;			   /**< Host gesture using MTCH6102 gesture codes. */
};

/** Number of bytes in the MTCH6102 configuration register block. */
#define MTCH6102_CONFIGURATION_REGISTER_COUNT \
	((uint8_t) (mtch6102_config_I2CAddr - mtch6102_config_NumberOfXChannels + 1U))

/** Convert a configuration-register ID into an index within the config array. */
#define MTCH6102_CONFIGURATION_INDEX(register_id) \
	((uint8_t) ((register_id) - mtch6102_config_NumberOfXChannels))

/**
 * @brief MTCH6102 driver configuration object.
 * @details This is a register-content container, not a raw I2C image. The
 *          driver writes the configuration array in register order, then
 *          applies the core control registers. All 15 channels must remain enabled,
 *          with at least three in each bank. MODE must be 1, 2, or 3; CMD
 *          may request CFG only. Host gesture timings are defined in the
 *          slider defaults; controller angle/velocity/timing registers do
 *          not control the host gesture engine.
 */
struct mtch6102_config_t {
	union mtch6102_cmd_register_t cmd;	 /**< Command register image; CMD is written last with the
											`cfg` bit set to apply the block below. */
	union mtch6102_mode_register_t mode; /**< Decode mode register image written to MODE. */
	union mtch6102_modecon_register_t modecon; /**< Raw-ADC control image written to MODECON. */
	/**
	 * Configuration register block written from NumberOfXChannels through
	 * VerticalGestureAngle, in register order. The I2CAddr register is part of
	 * the block but is never written, so the device keeps its fixed address.
	 */
	uint8_t configuration[MTCH6102_CONFIGURATION_REGISTER_COUNT];
};

/**
 * @brief Return the printable name for a MTCH6102 event identifier.
 *
 * @param event_id Event identifier from enum mtch6102_event_type.
 * @return Constant string for the event, or "Unknown" when @p event_id is invalid.
 */
const char* mtch6102_event_name(enum mtch6102_event_type event_id);

/**
 * @brief Classify one decoded sample into a stable MTCH6102 event identifier.
 *
 * The helper maps the host gesture code first, so swipe and click events are
 * reported even when the host touch has already been released. If no gesture
 * code is present, the helper falls back to touch-present and touch-released
 * events.
 *
 * @param sample Decoded touch sample, or NULL.
 * @return A value from enum mtch6102_event_type.
 */
enum mtch6102_event_type mtch6102_sample_event(const struct touch_sensor_sample_t* sample);

/**
 * @brief Report whether the MTCH6102 is initialized and configured.
 *
 * @retval true The controller has been detected and its register configuration was applied.
 * @retval false Initialization, probing, or configuration has not succeeded.
 */
bool mtch6102_is_ready(void);

/**
 * @brief Copy the most recently acquired host slider position.
 * @param pos Destination position structure.
 * @retval 0 A touch is present in the cached sample.
 * @retval -EINVAL pos is NULL.
 * @retval -EAGAIN Acquisition is stopped or no valid frame has been read.
 * @retval -ENODATA The cached sample reports no touch (x=y=0).
 */
int mtch6102_get_position(struct mtch6102_position* pos);

/**
 * @brief Populate the SensWear default touch configuration.
 * @details Fills the MTCH6102 configuration object with the default register
 *          contents used by the driver.
 *
 * @param config Destination configuration. Must not be NULL.
 */
void mtch6102_get_default_config(struct mtch6102_config_t* config);

/**
 * @brief Program the MTCH6102 touch configuration.
 *
 * Initialization is retried if an earlier probe failed. The complete register
 * sequence is applied under one programming scope. Passing NULL selects the
 * SensWear defaults. Transport failures retain their original errno.
 *
 * @param config Configuration to apply, or NULL for the defaults.
 * @retval 0 All configuration registers were written.
 * @retval -EINVAL The configuration is invalid.
 * @retval -EBUSY The driver is currently sampling.
 * @return A negative errno if a register transfer failed.
 */
int mtch6102_config(const struct mtch6102_config_t* config);

/**
 * @brief Initialize and probe the MTCH6102.
 *
 * Enables and validates the supply, probes the device, claims INT/SYNC as
 * inputs, arms the SYNC falling edge, and populates the default configuration.
 *
 * @retval 0 The shared bus was ready and the sensor responded (or the driver was
 *         already initialized).
 * @retval -ENODEV The bus was unavailable, the GPIO controller was not ready,
 *         or the sensor did not respond.
 * @retval -EIO A configuration, regulator, or GPIO transfer failed.
 */
int mtch6102_init(void);

/**
 * @brief Start interrupt-driven touch acquisition.
 *
 * Initializes/configures on demand, restores the configured acquisition
 * mode, resets host gesture state, and enables frame requests and recovery.
 *
 * @retval 0 Acquisition was started.
 * @return A negative errno propagated from mtch6102_init(), mtch6102_config(),
 *         or regulator setup.
 */
int mtch6102_start(void);

/** @brief Stop acquisition using standby, retaining shared-bus-safe rail power. */
void mtch6102_stop(void);

/**
 * @brief Handle an MTCH6102 interrupt.
 *
 * Reads SENSORVALUES between acquisition frames and publishes a host-decoded
 * event. p_param owns a sample which the consumer must release after use.
 * Call from thread context in response to mtch6102_Irq.
 *
 * @retval 0 The frame was processed (idle frames may produce no event).
 * @retval -EAGAIN Acquisition is stopped, a scan is active, or no new frame exists.
 * @return Negative errno on I2C failure, pool exhaustion, or queue overflow.
 */
int mtch6102_irq_handler(void);

/** Release exactly once after consuming a decoded event's p_param sample. */
void mtch6102_release_sample(const struct touch_sensor_sample_t* sample);

static inline bool touch_sensor_is_ready(void) {
	return mtch6102_is_ready();
}

static inline int touch_sensor_init(void) {
	return mtch6102_init();
}

static inline int touch_sensor_start(void) {
	return mtch6102_start();
}

static inline void touch_sensor_stop(void) {
	mtch6102_stop();
}

/** @} */

#endif /* MTCH6102_H_ */
